name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      BUILD_RERUN_COUNT: ${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@main

    - name: Install latest .NET SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        VERSION_MAJOR: '6'
        VERSION_BAND: '2xx'

    - name: Restore, Build, test, and pack
      uses: Elskom/build-dotnet@main
      with:
        TEST: true
