name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
    - name: .NET core build
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Restore, Build, test, and pack
      uses: Elskom/build-dotnet@main
      with:
        SOLUTION_FILE_PATH: GitBuildInfo.SourceGenerator.sln
        TEST: true
